#TESTS GENERATED BY CHATGPT
import pytest

from backend.app.poker.card import Card
from backend.app.poker.hand import Hand
from backend.app.poker.hand_evaluator import HandEvaluator
from backend.app.poker.hand_rank import HandRank


def make_hand(*cards: tuple[str, str]) -> Hand:
    hand = Hand()

    for rank, suit in cards:
        hand.add_card(Card(rank, suit))

    return hand


def test_high_card() -> None:
    hand = make_hand(
        ("A", "Spades"),
        ("K", "Hearts"),
        ("9", "Clubs"),
        ("5", "Diamonds"),
        ("3", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.HIGH_CARD


def test_pair() -> None:
    hand = make_hand(
        ("Q", "Spades"),
        ("Q", "Hearts"),
        ("A", "Clubs"),
        ("9", "Diamonds"),
        ("4", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.PAIR


def test_two_pair() -> None:
    hand = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("K", "Clubs"),
        ("K", "Diamonds"),
        ("3", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.TWO_PAIR


def test_three_of_a_kind() -> None:
    hand = make_hand(
        ("8", "Spades"),
        ("8", "Hearts"),
        ("8", "Clubs"),
        ("A", "Diamonds"),
        ("K", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.THREE_OF_A_KIND


def test_straight() -> None:
    hand = make_hand(
        ("10", "Spades"),
        ("J", "Hearts"),
        ("Q", "Clubs"),
        ("K", "Diamonds"),
        ("A", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.STRAIGHT


def test_flush() -> None:
    hand = make_hand(
        ("A", "Hearts"),
        ("J", "Hearts"),
        ("9", "Hearts"),
        ("6", "Hearts"),
        ("2", "Hearts"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.FLUSH


def test_full_house() -> None:
    hand = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("A", "Clubs"),
        ("K", "Diamonds"),
        ("K", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.FULL_HOUSE


def test_four_of_a_kind() -> None:
    hand = make_hand(
        ("9", "Spades"),
        ("9", "Hearts"),
        ("9", "Clubs"),
        ("9", "Diamonds"),
        ("A", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.FOUR_OF_A_KIND


def test_straight_flush() -> None:
    hand = make_hand(
        ("9", "Spades"),
        ("10", "Spades"),
        ("J", "Spades"),
        ("Q", "Spades"),
        ("K", "Spades"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.STRAIGHT_FLUSH

def test_higher_pair_wins() -> None:
    aces = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("8", "Clubs"),
        ("5", "Diamonds"),
        ("2", "Spades"),
    )

    kings = make_hand(
        ("K", "Spades"),
        ("K", "Hearts"),
        ("Q", "Clubs"),
        ("J", "Diamonds"),
        ("10", "Spades"),
    )

    assert HandEvaluator.evaluate(aces) > HandEvaluator.evaluate(kings)


def test_pair_kicker_breaks_tie() -> None:
    ace_kicker = make_hand(
        ("Q", "Spades"),
        ("Q", "Hearts"),
        ("A", "Clubs"),
        ("9", "Diamonds"),
        ("4", "Spades"),
    )

    king_kicker = make_hand(
        ("Q", "Clubs"),
        ("Q", "Diamonds"),
        ("K", "Spades"),
        ("J", "Hearts"),
        ("9", "Clubs"),
    )

    assert HandEvaluator.evaluate(ace_kicker) > HandEvaluator.evaluate(king_kicker)


def test_lower_kicker_can_break_tie() -> None:
    hand_a = make_hand(
        ("Q", "Spades"),
        ("Q", "Hearts"),
        ("A", "Clubs"),
        ("10", "Diamonds"),
        ("8", "Spades"),
    )

    hand_b = make_hand(
        ("Q", "Clubs"),
        ("Q", "Diamonds"),
        ("A", "Spades"),
        ("10", "Hearts"),
        ("7", "Clubs"),
    )

    assert HandEvaluator.evaluate(hand_a) > HandEvaluator.evaluate(hand_b)


def test_two_pair_compares_high_pair_first() -> None:
    aces_and_twos = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("2", "Clubs"),
        ("2", "Diamonds"),
        ("3", "Spades"),
    )

    kings_and_queens = make_hand(
        ("K", "Spades"),
        ("K", "Hearts"),
        ("Q", "Clubs"),
        ("Q", "Diamonds"),
        ("A", "Spades"),
    )

    assert (
        HandEvaluator.evaluate(aces_and_twos)
        > HandEvaluator.evaluate(kings_and_queens)
    )


def test_two_pair_compares_second_pair() -> None:
    aces_and_kings = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("K", "Clubs"),
        ("K", "Diamonds"),
        ("2", "Spades"),
    )

    aces_and_queens = make_hand(
        ("A", "Clubs"),
        ("A", "Diamonds"),
        ("Q", "Spades"),
        ("Q", "Hearts"),
        ("K", "Spades"),
    )

    assert (
        HandEvaluator.evaluate(aces_and_kings)
        > HandEvaluator.evaluate(aces_and_queens)
    )


def test_full_house_compares_three_of_a_kind_first() -> None:
    aces_full = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("A", "Clubs"),
        ("2", "Diamonds"),
        ("2", "Spades"),
    )

    kings_full = make_hand(
        ("K", "Spades"),
        ("K", "Hearts"),
        ("K", "Clubs"),
        ("A", "Diamonds"),
        ("A", "Spades"),
    )

    assert HandEvaluator.evaluate(aces_full) > HandEvaluator.evaluate(kings_full)


def test_flush_uses_all_kickers() -> None:
    ace_ten_flush = make_hand(
        ("A", "Hearts"),
        ("10", "Hearts"),
        ("8", "Hearts"),
        ("5", "Hearts"),
        ("2", "Hearts"),
    )

    ace_nine_flush = make_hand(
        ("A", "Spades"),
        ("9", "Spades"),
        ("8", "Spades"),
        ("5", "Spades"),
        ("2", "Spades"),
    )

    assert (
        HandEvaluator.evaluate(ace_ten_flush)
        > HandEvaluator.evaluate(ace_nine_flush)
    )

def test_ace_low_straight() -> None:
    wheel = make_hand(
        ("A", "Spades"),
        ("2", "Hearts"),
        ("3", "Clubs"),
        ("4", "Diamonds"),
        ("5", "Spades"),
    )

    result = HandEvaluator.evaluate(wheel)

    assert result[0] == HandRank.STRAIGHT


def test_six_high_straight_beats_ace_low_straight() -> None:
    wheel = make_hand(
        ("A", "Spades"),
        ("2", "Hearts"),
        ("3", "Clubs"),
        ("4", "Diamonds"),
        ("5", "Spades"),
    )

    six_high = make_hand(
        ("2", "Spades"),
        ("3", "Hearts"),
        ("4", "Clubs"),
        ("5", "Diamonds"),
        ("6", "Spades"),
    )

    assert HandEvaluator.evaluate(six_high) > HandEvaluator.evaluate(wheel)


def test_ace_low_straight_flush() -> None:
    hand = make_hand(
        ("A", "Clubs"),
        ("2", "Clubs"),
        ("3", "Clubs"),
        ("4", "Clubs"),
        ("5", "Clubs"),
    )

    result = HandEvaluator.evaluate(hand)

    assert result[0] == HandRank.STRAIGHT_FLUSH


def test_broadway_straight_is_ace_high() -> None:
    broadway = make_hand(
        ("10", "Spades"),
        ("J", "Hearts"),
        ("Q", "Clubs"),
        ("K", "Diamonds"),
        ("A", "Spades"),
    )

    king_high = make_hand(
        ("9", "Spades"),
        ("10", "Hearts"),
        ("J", "Clubs"),
        ("Q", "Diamonds"),
        ("K", "Spades"),
    )

    assert HandEvaluator.evaluate(broadway) > HandEvaluator.evaluate(king_high)

def test_evaluate_seven_finds_straight_flush() -> None:
    seven_cards = make_hand(
        ("9", "Spades"),
        ("10", "Spades"),
        ("J", "Spades"),
        ("Q", "Spades"),
        ("K", "Spades"),
        ("2", "Hearts"),
        ("A", "Diamonds"),
    )

    result = HandEvaluator.evaluate_seven(seven_cards)

    assert result[0] == HandRank.STRAIGHT_FLUSH


def test_evaluate_seven_finds_full_house() -> None:
    seven_cards = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("A", "Clubs"),
        ("K", "Spades"),
        ("K", "Hearts"),
        ("7", "Diamonds"),
        ("2", "Clubs"),
    )

    result = HandEvaluator.evaluate_seven(seven_cards)

    assert result[0] == HandRank.FULL_HOUSE


def test_evaluate_seven_chooses_higher_full_house() -> None:
    seven_cards = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("A", "Clubs"),
        ("K", "Spades"),
        ("K", "Hearts"),
        ("K", "Diamonds"),
        ("2", "Clubs"),
    )

    expected_best_five = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("A", "Clubs"),
        ("K", "Spades"),
        ("K", "Hearts"),
    )

    assert (
        HandEvaluator.evaluate_seven(seven_cards)
        == HandEvaluator.evaluate(expected_best_five)
    )


def test_evaluate_seven_finds_four_of_a_kind() -> None:
    seven_cards = make_hand(
        ("8", "Spades"),
        ("8", "Hearts"),
        ("8", "Clubs"),
        ("8", "Diamonds"),
        ("A", "Spades"),
        ("K", "Hearts"),
        ("2", "Clubs"),
    )

    result = HandEvaluator.evaluate_seven(seven_cards)

    assert result[0] == HandRank.FOUR_OF_A_KIND


def test_evaluate_seven_uses_best_kickers() -> None:
    seven_cards = make_hand(
        ("Q", "Spades"),
        ("Q", "Hearts"),
        ("A", "Clubs"),
        ("K", "Diamonds"),
        ("J", "Spades"),
        ("5", "Hearts"),
        ("2", "Clubs"),
    )

    expected_best_five = make_hand(
        ("Q", "Spades"),
        ("Q", "Hearts"),
        ("A", "Clubs"),
        ("K", "Diamonds"),
        ("J", "Spades"),
    )

    assert (
        HandEvaluator.evaluate_seven(seven_cards)
        == HandEvaluator.evaluate(expected_best_five)
    )


def test_evaluate_seven_chooses_flush_over_straight() -> None:
    seven_cards = make_hand(
        ("A", "Hearts"),
        ("J", "Hearts"),
        ("8", "Hearts"),
        ("5", "Hearts"),
        ("2", "Hearts"),
        ("10", "Clubs"),
        ("9", "Diamonds"),
    )

    result = HandEvaluator.evaluate_seven(seven_cards)

    assert result[0] == HandRank.FLUSH

def test_same_strength_hands_are_equal() -> None:
    hand_a = make_hand(
        ("A", "Spades"),
        ("A", "Hearts"),
        ("K", "Clubs"),
        ("10", "Diamonds"),
        ("5", "Spades"),
    )

    hand_b = make_hand(
        ("A", "Clubs"),
        ("A", "Diamonds"),
        ("K", "Spades"),
        ("10", "Hearts"),
        ("5", "Clubs"),
    )

    assert HandEvaluator.evaluate(hand_a) == HandEvaluator.evaluate(hand_b)